### ISSUE TITLE
Wrap cudaHostAlloc into __cudampi__HostAlloc

### ISSUE THREAD

**Issue by MAJ0RRR** [MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap#72]
Because now it seems it is only non custom function used in our apps so we might just wrap it to make it coherent.

**Comment by huwzpf** [comment]
Maybe initial memory allocation should be done on slaves also - TODO: check time profiling results and decide

**Comment by huwzpf** [comment]
It could be done, but \_\_cudampi\_\_ does not implement HostAlloc function as it just used for allocation on master side (since from user perspective slaves function like GPU devices so HostAlloc does not make sense in this context). One possible implementation would be:
```
__cudampi__HostAlloc(...) {
  if (localGpu) {
    cudaHostAlloc(...);
  } else {
    // Error, it is not possible
  }
}
```
Although question remains - is there any benefit of doint that ?

**Comment by huwzpf** [comment]
We aren't planning implement *every* cuda function override so I think it's generally good design choice to implement only those that actually communicate with remote nodes.
